_wandb:
    value:
        cli_version: 0.23.1
        e:
            gpl9mqvf9vpplgkw0r0x4fbqjtmilj0q:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 11
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1081101176832"
                        used: "27468480512"
                email: mikorin550@gmail.com
                executable: /home/debian/deeplearning-cis2018/.venv/bin/python3
                host: hp
                memory:
                    total: "16501096448"
                os: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.41
                program: /home/debian/deeplearning-cis2018/main.py
                python: CPython 3.13.5
                root: /home/debian/deeplearning-cis2018
                startedAt: "2025-12-26T08:29:26.845634Z"
                writerId: gpl9mqvf9vpplgkw0r0x4fbqjtmilj0q
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 13
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
learning_rate:
    value: 0.0001
num_epochs:
    value: 10
optimizer:
    value: AdamW
scheduler:
    value: ReduceLROnPlateau
